sonar.projectKey=Thierno-dtd_system_metrics_agent
sonar.organization=thierno-dtd
sonar.projectName=system_metrics_agent

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
